name: rx_state_dart
description: RX-based Dart state-manager library
version: 1.0.1
repository: https://github.com/IIPEKOLICT/rx-state-dart

environment:
  sdk: '>=2.19.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
