name: rx_state_dart
version: 1.0.2
description: RX-based Dart state-manager library
repository: https://github.com/evgenii-shcherbakov/libraries/tree/main/dart/rx_state_dart

environment: 
  sdk: '>=2.19.4 <3.0.0'

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.21.0
