name: 'Kotlin'

on:
  push:
    paths:
      - 'kotlin/**'
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
    paths:
      - 'kotlin/**'
    branches:
      - 'main'

env:
  KEYSTORE_HOST: '${{ secrets.KEYSTORE_HOST }}'
  KEYSTORE_ACCESS_TOKEN: '${{ secrets.KEYSTORE_ACCESS_TOKEN }}'

jobs:
  Dart:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2
      - uses: 'actions/setup-java@v2'
        with:
          distribution: 'zulu'
          java-version: 19
      - name: 'Build libraries with changes'
        if: ${{ github.event_name == 'pull_request' }}
        run: 'chmod +x scripts/kotlin.sh && scripts/kotlin.sh build'
      - name: 'Build & publish libraries with changes'
        if: ${{ github.event_name == 'push' }}
        run: 'chmod +x scripts/kotlin.sh && scripts/kotlin.sh publish'
