name: 'Test (handle tag)'

on:
  repository_dispatch:
    types:
      - 'tag-created'

env:
  GIT_USERNAME: '${{ secrets.GIT_USERNAME }}'
  GIT_EMAIL: '${{ secrets.GIT_EMAIL }}'

jobs:
  Main:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2
      - uses: 'dart-lang/setup-dart@v1'
      - name: 'Set tag variable'
        run: 'echo GIT_TAG_NAME=${{ github.event.client_payload.tag }} >> $GITHUB_ENV'
      - name: 'Build & publish changed library'
        run: 'chmod +x scripts/dart.sh && scripts/dart.sh publish'
